# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/college_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Siddhant@12

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Allow Spring to handle JSON errors
server.error.whitelabel.enabled=false
